name: XML Sync - Stilimon

on:
  schedule:
    # Her 6 saatte bir çalışır (UTC zaman diliminde)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Manuel çalıştırma için

jobs:
  sync-xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run XML sync script
      run: python stilmon.py
      
